name: 'Main'

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile"
        required: true
        default: "BASIC"
        type: choice
        options:
          - "BASIC"
          - "STRESS"
          - "SINGLE"
  push:
    branches:
      - 'main'

permissions:
  contents: read    # This is required for actions/checkout

env:
  PROFILE: ${{ github.event.input.profile }}

jobs:
  # Gatling test
  gatling:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start app mock
        working-directory: app-mock
        run: |
          docker build -t app-mock:v1 .
          
          docker run -d --rm -p 8080:8080 --name app-mock app-mock:v1

      - name: Run gatling test
        id: gatling-test
        working-directory: gatling
        run: |
          mvn --file pom.xml gatling:test

      - name: Uploading artifacts
        uses: actions/upload-artifact@master
        with:
          name: RESULTS
          path: gatling/results/
          retention-days: 1
